name: Main workflow

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '!docs/building-msvc.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'qttabbar/build/**'
    branches: [ vs2019 ]
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '!docs/building-msvc.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - 'lib/xdg/**'
      - 'snap/**'
      - 'qttabbar/build/**'
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest        
    steps:
     - uses: actions/checkout@master
     - name: Core Build
       run: msbuild "QTTabBar Rebirth.sln" /t:Rebuild /property:Configuration=Release /property:Platform="Any CPU"
       
